# Generated by Django 5.0.6 on 2024-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
