# Generated by Django 5.0.6 on 2024-08-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="name",
        ),
        migrations.AddField(
            model_name="subscriber",
            name="accepted_terms",
            field=models.BooleanField(default=False),
        ),
    ]
