# Generated by Django 5.0.6 on 2024-09-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_remove_subscriber_name_subscriber_accepted_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=254)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Publish", "Publish")],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
