# Generated by Django 5.0.6 on 2024-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_newsletter_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Save as Draft"),
                    ("finalized", "Save as Finalized Version"),
                    ("send", "Save and Send Newsletter Now"),
                    ("done", "Done and Sent"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
