# Generated by Django 5.0.6 on 2024-07-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_alter_subcategory_name"),
        ("profiles", "0002_userprofile_default_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Mandala", "Mandala"),
                            ("Flower", "Flower"),
                            ("Turtle", "Turtle"),
                            ("Whale", "Whale"),
                            ("Octopus", "Octopus"),
                            ("Fish", "Fish"),
                            ("Waves", "Waves"),
                            ("Abstract", "Abstract"),
                            ("Surprise Me", "Surprise Me"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Decorative Art",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("message_read", models.BooleanField(default=False)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.TextField(max_length=3000)),
                (
                    "board_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Shortboard", "Shortboard"),
                            ("Fishboard", "Fishboard"),
                            ("Malibu", "Malibu"),
                            ("Funboard", "Funboard"),
                            ("Longboard", "Longboard"),
                            ("Gun", "Gun"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tail",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Swallow", "Swallow"),
                            ("Round", "Round"),
                            ("Pin", "Pin"),
                            ("Square", "Square"),
                            ("Squash", "Squash"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("body_height", models.IntegerField(blank=True, null=True)),
                ("body_weight", models.IntegerField(blank=True, null=True)),
                ("board_length", models.IntegerField(blank=True, null=True)),
                ("board_volume", models.IntegerField(blank=True, null=True)),
                (
                    "skill_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Beginner Intermediate", "Beginner Intermediate"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Pro", "Pro"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "surf_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cruising", "Cruising"),
                            ("Carving", "Carving"),
                            ("Aerials", "Aerials"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "wave_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Knee", "Knee"),
                            ("Waist", "Waist"),
                            ("Chest", "Chest"),
                            ("Head", "Head"),
                            ("Head+", "Head+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "wave_power",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Weak", "Weak"),
                            ("Medium", "Medium"),
                            ("Strong", "Strong"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "color_theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wooden", "Wooden"),
                            ("Multicolor", "Multicolor"),
                            ("Bright Colors", "Bright Colors"),
                            ("Natural Colors", "Natural Colors"),
                            ("Light", "Light"),
                            ("Dark", "Dark"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "art",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.art",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Contact",
            },
        ),
    ]
