# Generated by Django 5.0.6 on 2024-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="none", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(default="nothing", max_length=100),
            preserve_default=False,
        ),
    ]
