# Generated by Django 5.0.6 on 2024-07-11 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_email_alter_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="board_length",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="board_volume",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="body_height",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(250)],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="body_weight",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(500)],
            ),
        ),
    ]
