# Generated by Django 5.0.6 on 2024-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
