# Generated by Django 5.0.6 on 2024-07-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("checkout", "0002_alter_discountcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.discountcode",
            ),
        ),
        migrations.DeleteModel(
            name="DiscountCode",
        ),
    ]
