# Generated by Django 5.0.6 on 2024-07-09 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(max_length=5000, verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=1000, verbose_name="Question"),
        ),
    ]
