# Generated by Django 5.0.6 on 2024-07-09 09:42

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_faq_options_faq_created_at_alter_faq_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="sss-resources/",
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="content",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="sss-about/",
            ),
        ),
        migrations.AlterField(
            model_name="customsurfboard",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="customsurfboard",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="sss-custom_surfboards/",
            ),
        ),
    ]
