# Generated by Django 5.0.6 on 2024-09-11 08:42

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_resource_description_resource_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[400, None],
                upload_to="sss-about/",
            ),
        ),
    ]
