# Generated by Django 5.0.6 on 2024-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "active",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="Yes",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Codes",
                "verbose_name_plural": "Discount Codes",
            },
        ),
    ]
