# Generated by Django 5.0.6 on 2024-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Publish", "Publish")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
