# Generated by Django 5.0.6 on 2024-06-25 18:01

import django.db.models.deletion
import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=djrichtextfield.models.RichTextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.subcategory",
            ),
        ),
    ]
