# Generated by Django 5.0.6 on 2024-06-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_description_alter_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("Shaping", "Shaping"),
                    ("Materials", "Materials & Tools"),
                    ("Accessories", "Accessories"),
                    ("Surfing", "Surfing"),
                ],
                max_length=50,
            ),
        ),
    ]
