# Generated by Django 5.0.6 on 2024-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_subcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
